name: tasks
description: "A task management Flutter application."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_database: ^12.0.0
  firebase_auth: ^6.0.0
  cloud_functions: ^6.0.0
  google_sign_in: ^7.1.1
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
