// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
  return android; // TEMP stub – run `flutterfire configure` to replace
      case TargetPlatform.iOS:
  return ios; // TEMP stub
      case TargetPlatform.macOS:
  return macos; // TEMP stub
      case TargetPlatform.windows:
  return windows; // Added for desktop build
      case TargetPlatform.linux:
  return linux; // TEMP stub
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDPh3tLM8-EeVv0ihO8b6JJdNrJAhfJnQ',
    appId: '1:938074109660:web:c7da53da8d615ca8bce619',
    messagingSenderId: '938074109660',
    projectId: 'nandhu-firelogin',
    authDomain: 'nandhu-firelogin.firebaseapp.com',
    databaseURL: 'https://nandhu-firelogin-default-rtdb.firebaseio.com/',
    storageBucket: 'nandhu-firelogin.firebasestorage.app',
    measurementId: 'G-5ZRTDZVJZH',
  );

  // ---- TEMP STUB CONFIGS FOR DESKTOP / MOBILE ----
  // Replace by running: flutterfire configure --platforms=android,ios,macos,windows,linux,web
  // Using same web values (may NOT work fully for native SDKs). Provided only to allow build.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDPh3tLM8-EeVv0ihO8b6JJdNrJAhfJnQ',
    appId: '1:938074109660:android:stubbed',
    messagingSenderId: '938074109660',
    projectId: 'nandhu-firelogin',
    databaseURL: 'https://nandhu-firelogin-default-rtdb.firebaseio.com/',
    storageBucket: 'nandhu-firelogin.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDPh3tLM8-EeVv0ihO8b6JJdNrJAhfJnQ',
    appId: '1:938074109660:ios:stubbed',
    messagingSenderId: '938074109660',
    projectId: 'nandhu-firelogin',
    databaseURL: 'https://nandhu-firelogin-default-rtdb.firebaseio.com/',
    storageBucket: 'nandhu-firelogin.firebasestorage.app',
    iosBundleId: 'com.example.stub',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDPh3tLM8-EeVv0ihO8b6JJdNrJAhfJnQ',
    appId: '1:938074109660:macos:stubbed',
    messagingSenderId: '938074109660',
    projectId: 'nandhu-firelogin',
    databaseURL: 'https://nandhu-firelogin-default-rtdb.firebaseio.com/',
    storageBucket: 'nandhu-firelogin.firebasestorage.app',
    iosBundleId: 'com.example.stub',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDPh3tLM8-EeVv0ihO8b6JJdNrJAhfJnQ',
    appId: '1:938074109660:windows:stubbed',
    messagingSenderId: '938074109660',
    projectId: 'nandhu-firelogin',
    databaseURL: 'https://nandhu-firelogin-default-rtdb.firebaseio.com/',
    storageBucket: 'nandhu-firelogin.firebasestorage.app',
  );
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBDPh3tLM8-EeVv0ihO8b6JJdNrJAhfJnQ',
    appId: '1:938074109660:linux:stubbed',
    messagingSenderId: '938074109660',
    projectId: 'nandhu-firelogin',
    databaseURL: 'https://nandhu-firelogin-default-rtdb.firebaseio.com/',
    storageBucket: 'nandhu-firelogin.firebasestorage.app',
  );

}